#+TITLE: QoolUI 控件库说明
#+AUTHOR: xiii_1991

* 概述信息（FAQ）
我不是一个专业的开发者，充其量只能算是一个「电子设计爱好者」吧。
所以，这个东西其实最早是自己开发小工具的时候使用的界面库，后来边学 QML 边制作，就搞成了一个库。

** 关于 Qt 插件形式
但是这个库并不是使用 Qt 的插件形式使用的，而是需要代码导入进去再使用。
（我不会承认是那样太麻烦了我不会弄的……）
其实另一个想法是，把其中 C++ 实现的一部分使用 Python 重新实现以下，这样就可以在重用 QML 文件的同时支持 Py 啦！

** 关于跨平台
理论上这套控件是跨平台的，因为全部都是 QML/C++/Py 实现的。
但是好像因为编译器的区别写法会有一些差别？我只是业余的我也不懂。
我现在主要用 Mac，所以 Mac 上面编译一定是过的，Windows 和 Linux 上面测试不会那么及时。
所以 Win 和 Lin 上面编译报错的话，请再等等吧！

** 关于一些控件的创意意见与建议
欢迎各种想法！如果你想要我加进去的话，欢迎联系我！

** 关于发布
目前的发布平台：
- GITEE
- GITHUB

一些开发过程和讲解发表在 BILIBILI

* 自带的示例程序
为了方便测试和介绍，本项目自带一个空间实例程序。
下载后使用 QtCreator 打开项目，直接运行应该就可以打开它了。
里面可以开心地玩耍！

如果只要使用 QoolUI 控件库的话，忽略它就可以啦。

* 具体使用说明
QoolUI 目前分成了几个包，使用地时候请注意自己导入
** Qool.asssets
这里面是一些控件用到的数据文件
- color_name_table.csv
  这是颜色选择器的颜色名数据表。需要它才能显示颜色的名称。
** Qool.Components
这里面是基本的一些控件的基本组件。都是功能单一高度抽象的东西。

- Colorist.qml
  这个没什么大用，是 C++ 版本 Colorist 的 QML 重新包装。包装的主要目的是为了以后 Python 兼容性。

- ControlLockedCover.qml
  这个是所有控件锁定状态叠层的预置。

- CutCornerBox.qml
  这个是 QoolUI 的核心，缺角矩形的 QML 包装。
  后台实际上仍然是 C++ 实现的。包装一下的目的是为了以后方便支持 Python 实现。

- CutCornerControlBack.qml
  这个是缺角矩形的控件背景包装，基于 CutCornerBox。

  基本属性包括：
  - alterBackgroundColor
    如果有多重控件嵌套的话，背景颜色不好看，这个开关可以切换背景是否切换为另一种预置方案。

  - title
    控件的标题文本。控件背景会自动在右上角渲染一个标题文本。

  - showTitle
    是否渲染标题文本。此选项和切角宽度共同决定内部填充框的范围。

  - titleText
    标题文本的实体 alias。这个导出只是为了方便子类进行魔改。
